add_subdirectory(Core)
add_subdirectory(Eigen)
add_library(OpenCAXSolver INTERFACE)
add_library(OpenCAX::Solver ALIAS OpenCAXSolver)
target_link_libraries(OpenCAXSolver INTERFACE OpenCAX::SolverCore OpenCAX::SolverEigen)
target_include_directories(OpenCAXSolver INTERFACE $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:include>)
set_target_properties(OpenCAXSolver PROPERTIES EXPORT_NAME Solver)
install(TARGETS OpenCAXSolver EXPORT OpenCAXTargets)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/include/OpenCAX/Solver DESTINATION include/OpenCAX)
